// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHub.DB;

#nullable disable

namespace SmartHub.DB.Migrations
{
    [DbContext(typeof(SmartHubAPIContext))]
    [Migration("20241118023250_CompanyDeviceModelValidationMigration")]
    partial class CompanyDeviceModelValidationMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Validator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Domain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotosJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Devices", (string)null);

                    b.HasDiscriminator<string>("DeviceType").HasValue("Device");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Hardware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HardwareType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Online")
                        .HasColumnType("bit");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("HomeId");

                    b.ToTable("Hardwares", (string)null);

                    b.HasDiscriminator<string>("HardwareType").HasValue("Hardware");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rooms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HardwareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HardwareId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Domain.NotificationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationMembers");
                });

            modelBuilder.Entity("Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("745be69a-a826-4681-afd6-fb078077e5bb"),
                            Name = "getnotifications-notification"
                        },
                        new
                        {
                            Id = new Guid("d5e44a76-0591-4d28-8a55-c4590a1c7cc6"),
                            Name = "open-windowsensor"
                        },
                        new
                        {
                            Id = new Guid("5be60e33-7852-4448-ab98-34df4f167722"),
                            Name = "close-windowsensor"
                        },
                        new
                        {
                            Id = new Guid("a00824d0-de14-4255-a2fd-b432239d0fd0"),
                            Name = "motiondetection-camera"
                        },
                        new
                        {
                            Id = new Guid("283a5f30-d476-4a1a-920e-3f88fdb244a9"),
                            Name = "persondetection-camera"
                        },
                        new
                        {
                            Id = new Guid("ebded65c-08d4-499c-b40d-3aebd18ce3f9"),
                            Name = "getdevices-devices"
                        },
                        new
                        {
                            Id = new Guid("d92f5e63-0235-42fe-beb4-d108f778e799"),
                            Name = "getdevicetypes-devicetype"
                        },
                        new
                        {
                            Id = new Guid("b9076b7e-ea7d-427d-8ea5-9ed2730642e2"),
                            Name = "motiondetection-motionsensor"
                        },
                        new
                        {
                            Id = new Guid("36003e34-d4ee-4d69-9e17-69b75a912717"),
                            Name = "on-smartlamp"
                        },
                        new
                        {
                            Id = new Guid("6bfe1e72-fb05-48a9-af9e-b64663e5bd0c"),
                            Name = "off-smartlamp"
                        },
                        new
                        {
                            Id = new Guid("1d6d80d6-878a-4f3d-a24e-fc82a6b7a044"),
                            Name = "getpermissions-home"
                        },
                        new
                        {
                            Id = new Guid("1cf5102a-a990-4897-a7a3-20e3a7a8a9c4"),
                            Name = "createcompany-companies"
                        },
                        new
                        {
                            Id = new Guid("55d423b0-c045-42ec-b3d1-53059dd9a81f"),
                            Name = "addsensor-windowsensor"
                        },
                        new
                        {
                            Id = new Guid("f1861871-1dc0-48e8-b464-cc5414ec701c"),
                            Name = "addmotionsensor-motionsensor"
                        },
                        new
                        {
                            Id = new Guid("3105272f-285f-4510-827d-68345265e5a4"),
                            Name = "addcamera-camera"
                        },
                        new
                        {
                            Id = new Guid("2fbb8681-f44c-408a-9da9-83be613713eb"),
                            Name = "addhomeownerpermission-homeowner"
                        },
                        new
                        {
                            Id = new Guid("1bd3df79-28a6-43f5-86ba-88fbb26a3867"),
                            Name = "addsmartlamp-smartlamp"
                        },
                        new
                        {
                            Id = new Guid("b4ff06ef-4ab5-4320-a328-34b102cf18b1"),
                            Name = "importdevices-devices"
                        },
                        new
                        {
                            Id = new Guid("48ea25dc-0af9-4860-857e-618b566a38da"),
                            Name = "getimporters-devices"
                        },
                        new
                        {
                            Id = new Guid("0ec09ab0-f4ee-4daf-a358-15e014327b12"),
                            Name = "getcompanyuser-companies"
                        },
                        new
                        {
                            Id = new Guid("d87de716-d773-41b7-850a-2e067b8058ea"),
                            Name = "getdevicemodelvalidators-devices"
                        },
                        new
                        {
                            Id = new Guid("afd88a6d-94e1-49db-8326-61f25425f751"),
                            Name = "selectdevicemodelvalidator-devices"
                        },
                        new
                        {
                            Id = new Guid("2797a995-92e9-4cc6-92a6-524cc8e37ad0"),
                            Name = "createadminaccount-administrator"
                        },
                        new
                        {
                            Id = new Guid("d7cb89bc-3824-48f3-89f7-6b13a822b1c8"),
                            Name = "deleteadminaccount-administrator"
                        },
                        new
                        {
                            Id = new Guid("3ec1778e-f770-4dfe-af78-81f8d888c013"),
                            Name = "createcompanyowneraccount-companyowner"
                        },
                        new
                        {
                            Id = new Guid("21aa7240-2887-418d-bbd4-ebc65b268642"),
                            Name = "getaccounts-accounts"
                        },
                        new
                        {
                            Id = new Guid("f1ec4f0d-1f30-4433-9742-8190339f60aa"),
                            Name = "getcompany-companies"
                        },
                        new
                        {
                            Id = new Guid("ddd33fee-dc86-4451-bc25-1a5a6fa9837f"),
                            Name = "addhomeownerpermission-homeowner"
                        },
                        new
                        {
                            Id = new Guid("6f1153e0-a140-41b4-9430-f27b97b4755d"),
                            Name = "getrooms-home"
                        },
                        new
                        {
                            Id = new Guid("ffb242b0-6803-458a-b644-2af27bfcd628"),
                            Name = "newhome-home"
                        },
                        new
                        {
                            Id = new Guid("3df86421-0c34-43b9-a68b-df2a0065462b"),
                            Name = "addmember-members"
                        },
                        new
                        {
                            Id = new Guid("d13c1b7f-43d8-4242-8db1-5a5d8e8e088e"),
                            Name = "adddevice-home"
                        },
                        new
                        {
                            Id = new Guid("18382c9f-daa5-4277-a834-3705156ca653"),
                            Name = "getmembers-members"
                        },
                        new
                        {
                            Id = new Guid("e406e50c-23c0-4944-9ec1-aa060c8fa935"),
                            Name = "getdevices-home"
                        },
                        new
                        {
                            Id = new Guid("5e8e4361-74d0-4207-87d9-e2ca1b016fd4"),
                            Name = "addnotificationmembers-members"
                        },
                        new
                        {
                            Id = new Guid("3fbe914f-5dfb-4283-baef-ef8f2b8174a0"),
                            Name = "updatenamedevice-home"
                        },
                        new
                        {
                            Id = new Guid("81cc5bdb-7ffb-4c76-9a6b-663d000a869e"),
                            Name = "addmotionsensor-motionsensor"
                        },
                        new
                        {
                            Id = new Guid("df2a46d3-346f-4e08-b090-b7a81e3aa650"),
                            Name = "gethomes-user"
                        },
                        new
                        {
                            Id = new Guid("4d055f14-cf7a-40a5-b8ac-3c5f64b539b2"),
                            Name = "addpermission-members"
                        },
                        new
                        {
                            Id = new Guid("0f0baebe-81e1-4313-ad63-90bb0a7e8e64"),
                            Name = "addrooms-home"
                        },
                        new
                        {
                            Id = new Guid("f789a3c1-3ac6-45bd-9277-458249206097"),
                            Name = "updateroomdevice-home"
                        });
                });

            modelBuilder.Entity("Domain.SessionUser", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296"),
                            CreatedAt = new DateTime(2024, 11, 17, 23, 32, 50, 578, DateTimeKind.Local).AddTicks(3537),
                            Email = "rogerfederer@tennis.com",
                            Name = "Roger",
                            Password = "Federer@123",
                            ProfilePhoto = "federer.jpg",
                            Roles = "[0]",
                            Surname = "Federer"
                        },
                        new
                        {
                            Id = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11"),
                            CreatedAt = new DateTime(2024, 11, 17, 23, 32, 50, 578, DateTimeKind.Local).AddTicks(3559),
                            Email = "rafaelnadal@tennis.com",
                            Name = "Rafael",
                            Password = "Nadal@123",
                            ProfilePhoto = "nadal.jpg",
                            Roles = "[0]",
                            Surname = "Nadal"
                        },
                        new
                        {
                            Id = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37"),
                            CreatedAt = new DateTime(2024, 11, 17, 23, 32, 50, 578, DateTimeKind.Local).AddTicks(3563),
                            Email = "serenawilliams@tennis.com",
                            Name = "Serena",
                            Password = "Serena@123",
                            ProfilePhoto = "serena.jpg",
                            Roles = "[2]",
                            Surname = "Williams"
                        },
                        new
                        {
                            Id = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3"),
                            CreatedAt = new DateTime(2024, 11, 17, 23, 32, 50, 578, DateTimeKind.Local).AddTicks(3566),
                            Email = "novakdjokovic@tennis.com",
                            Name = "Novak",
                            Password = "Djokovic@123",
                            ProfilePhoto = "djokovic.jpg",
                            Roles = "[2,1]",
                            Surname = "Djokovic"
                        },
                        new
                        {
                            Id = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97"),
                            CreatedAt = new DateTime(2024, 11, 17, 23, 32, 50, 578, DateTimeKind.Local).AddTicks(3569),
                            Email = "steffigraf@tennis.com",
                            Name = "Steffi",
                            Password = "Steffi@123",
                            ProfilePhoto = "graf.jpg",
                            Roles = "[1]",
                            Surname = "Graf"
                        },
                        new
                        {
                            Id = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2"),
                            CreatedAt = new DateTime(2024, 11, 17, 23, 32, 50, 578, DateTimeKind.Local).AddTicks(3592),
                            Email = "andreagassi@tennis.com",
                            Name = "Andre",
                            Password = "Agassi@123",
                            ProfilePhoto = "agassi.jpg",
                            Roles = "[1]",
                            Surname = "Agassi"
                        },
                        new
                        {
                            Id = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73"),
                            CreatedAt = new DateTime(2024, 11, 17, 23, 32, 50, 578, DateTimeKind.Local).AddTicks(3595),
                            Email = "petesampras@tennis.com",
                            Name = "Pete",
                            Password = "Sampras@123",
                            ProfilePhoto = "sampras.jpg",
                            Roles = "[1]",
                            Surname = "Sampras"
                        },
                        new
                        {
                            Id = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3"),
                            CreatedAt = new DateTime(2024, 11, 17, 23, 32, 50, 578, DateTimeKind.Local).AddTicks(3598),
                            Email = "martinanavratilova@tennis.com",
                            Name = "Martina",
                            Password = "Navratilova@123",
                            ProfilePhoto = "navratilova.jpg",
                            Roles = "[1]",
                            Surname = "Navratilova"
                        },
                        new
                        {
                            Id = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3"),
                            CreatedAt = new DateTime(2024, 11, 17, 23, 32, 50, 578, DateTimeKind.Local).AddTicks(3601),
                            Email = "johnmcenroe@tennis.com",
                            Name = "John",
                            Password = "McEnroe@123",
                            ProfilePhoto = "mcenroe.jpg",
                            Roles = "[2]",
                            Surname = "McEnroe"
                        },
                        new
                        {
                            Id = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4"),
                            CreatedAt = new DateTime(2024, 11, 17, 23, 32, 50, 578, DateTimeKind.Local).AddTicks(3605),
                            Email = "billiejeanking@tennis.com",
                            Name = "Billie",
                            Password = "King@123",
                            ProfilePhoto = "king.jpg",
                            Roles = "[0]",
                            Surname = "Jean King"
                        });
                });

            modelBuilder.Entity("Domain.UserHomePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHomePermissions");
                });

            modelBuilder.Entity("Domain.UserPermissions", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionId = new Guid("1cf5102a-a990-4897-a7a3-20e3a7a8a9c4"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("55d423b0-c045-42ec-b3d1-53059dd9a81f"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("f1861871-1dc0-48e8-b464-cc5414ec701c"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("3105272f-285f-4510-827d-68345265e5a4"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("2fbb8681-f44c-408a-9da9-83be613713eb"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("1bd3df79-28a6-43f5-86ba-88fbb26a3867"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("b4ff06ef-4ab5-4320-a328-34b102cf18b1"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("48ea25dc-0af9-4860-857e-618b566a38da"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("0ec09ab0-f4ee-4daf-a358-15e014327b12"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("d87de716-d773-41b7-850a-2e067b8058ea"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("afd88a6d-94e1-49db-8326-61f25425f751"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("745be69a-a826-4681-afd6-fb078077e5bb"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("d5e44a76-0591-4d28-8a55-c4590a1c7cc6"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("5be60e33-7852-4448-ab98-34df4f167722"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("a00824d0-de14-4255-a2fd-b432239d0fd0"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("283a5f30-d476-4a1a-920e-3f88fdb244a9"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("ebded65c-08d4-499c-b40d-3aebd18ce3f9"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("d92f5e63-0235-42fe-beb4-d108f778e799"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("b9076b7e-ea7d-427d-8ea5-9ed2730642e2"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("36003e34-d4ee-4d69-9e17-69b75a912717"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("6bfe1e72-fb05-48a9-af9e-b64663e5bd0c"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("1d6d80d6-878a-4f3d-a24e-fc82a6b7a044"),
                            UserId = new Guid("771457c4-087e-43f2-9ed0-80f7167c2296")
                        },
                        new
                        {
                            PermissionId = new Guid("1cf5102a-a990-4897-a7a3-20e3a7a8a9c4"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("55d423b0-c045-42ec-b3d1-53059dd9a81f"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("f1861871-1dc0-48e8-b464-cc5414ec701c"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("3105272f-285f-4510-827d-68345265e5a4"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("2fbb8681-f44c-408a-9da9-83be613713eb"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("1bd3df79-28a6-43f5-86ba-88fbb26a3867"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("b4ff06ef-4ab5-4320-a328-34b102cf18b1"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("48ea25dc-0af9-4860-857e-618b566a38da"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("0ec09ab0-f4ee-4daf-a358-15e014327b12"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("d87de716-d773-41b7-850a-2e067b8058ea"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("afd88a6d-94e1-49db-8326-61f25425f751"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("745be69a-a826-4681-afd6-fb078077e5bb"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("d5e44a76-0591-4d28-8a55-c4590a1c7cc6"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("5be60e33-7852-4448-ab98-34df4f167722"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("a00824d0-de14-4255-a2fd-b432239d0fd0"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("283a5f30-d476-4a1a-920e-3f88fdb244a9"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("ebded65c-08d4-499c-b40d-3aebd18ce3f9"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("d92f5e63-0235-42fe-beb4-d108f778e799"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("b9076b7e-ea7d-427d-8ea5-9ed2730642e2"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("36003e34-d4ee-4d69-9e17-69b75a912717"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("6bfe1e72-fb05-48a9-af9e-b64663e5bd0c"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("1d6d80d6-878a-4f3d-a24e-fc82a6b7a044"),
                            UserId = new Guid("fb07e945-7551-4dd3-8dba-1e0ab57f0e11")
                        },
                        new
                        {
                            PermissionId = new Guid("2797a995-92e9-4cc6-92a6-524cc8e37ad0"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("d7cb89bc-3824-48f3-89f7-6b13a822b1c8"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("3ec1778e-f770-4dfe-af78-81f8d888c013"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("21aa7240-2887-418d-bbd4-ebc65b268642"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("f1ec4f0d-1f30-4433-9742-8190339f60aa"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("ddd33fee-dc86-4451-bc25-1a5a6fa9837f"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("745be69a-a826-4681-afd6-fb078077e5bb"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("d5e44a76-0591-4d28-8a55-c4590a1c7cc6"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("5be60e33-7852-4448-ab98-34df4f167722"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("a00824d0-de14-4255-a2fd-b432239d0fd0"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("283a5f30-d476-4a1a-920e-3f88fdb244a9"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("ebded65c-08d4-499c-b40d-3aebd18ce3f9"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("d92f5e63-0235-42fe-beb4-d108f778e799"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("b9076b7e-ea7d-427d-8ea5-9ed2730642e2"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("36003e34-d4ee-4d69-9e17-69b75a912717"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("6bfe1e72-fb05-48a9-af9e-b64663e5bd0c"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("1d6d80d6-878a-4f3d-a24e-fc82a6b7a044"),
                            UserId = new Guid("568267a9-5fbb-4371-8275-242ae3ae1d37")
                        },
                        new
                        {
                            PermissionId = new Guid("2797a995-92e9-4cc6-92a6-524cc8e37ad0"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("d7cb89bc-3824-48f3-89f7-6b13a822b1c8"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("3ec1778e-f770-4dfe-af78-81f8d888c013"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("21aa7240-2887-418d-bbd4-ebc65b268642"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("f1ec4f0d-1f30-4433-9742-8190339f60aa"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("ddd33fee-dc86-4451-bc25-1a5a6fa9837f"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("6f1153e0-a140-41b4-9430-f27b97b4755d"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("ffb242b0-6803-458a-b644-2af27bfcd628"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("3df86421-0c34-43b9-a68b-df2a0065462b"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("d13c1b7f-43d8-4242-8db1-5a5d8e8e088e"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("18382c9f-daa5-4277-a834-3705156ca653"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("e406e50c-23c0-4944-9ec1-aa060c8fa935"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("5e8e4361-74d0-4207-87d9-e2ca1b016fd4"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("3fbe914f-5dfb-4283-baef-ef8f2b8174a0"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("81cc5bdb-7ffb-4c76-9a6b-663d000a869e"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("df2a46d3-346f-4e08-b090-b7a81e3aa650"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("4d055f14-cf7a-40a5-b8ac-3c5f64b539b2"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("0f0baebe-81e1-4313-ad63-90bb0a7e8e64"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("f789a3c1-3ac6-45bd-9277-458249206097"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("745be69a-a826-4681-afd6-fb078077e5bb"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("d5e44a76-0591-4d28-8a55-c4590a1c7cc6"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("5be60e33-7852-4448-ab98-34df4f167722"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("a00824d0-de14-4255-a2fd-b432239d0fd0"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("283a5f30-d476-4a1a-920e-3f88fdb244a9"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("ebded65c-08d4-499c-b40d-3aebd18ce3f9"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("d92f5e63-0235-42fe-beb4-d108f778e799"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("b9076b7e-ea7d-427d-8ea5-9ed2730642e2"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("36003e34-d4ee-4d69-9e17-69b75a912717"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("6bfe1e72-fb05-48a9-af9e-b64663e5bd0c"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("1d6d80d6-878a-4f3d-a24e-fc82a6b7a044"),
                            UserId = new Guid("7931eb7d-1f2f-4fb8-b0d9-7eac762640f3")
                        },
                        new
                        {
                            PermissionId = new Guid("6f1153e0-a140-41b4-9430-f27b97b4755d"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("ffb242b0-6803-458a-b644-2af27bfcd628"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("3df86421-0c34-43b9-a68b-df2a0065462b"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("d13c1b7f-43d8-4242-8db1-5a5d8e8e088e"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("18382c9f-daa5-4277-a834-3705156ca653"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("e406e50c-23c0-4944-9ec1-aa060c8fa935"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("5e8e4361-74d0-4207-87d9-e2ca1b016fd4"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("3fbe914f-5dfb-4283-baef-ef8f2b8174a0"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("81cc5bdb-7ffb-4c76-9a6b-663d000a869e"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("df2a46d3-346f-4e08-b090-b7a81e3aa650"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("4d055f14-cf7a-40a5-b8ac-3c5f64b539b2"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("0f0baebe-81e1-4313-ad63-90bb0a7e8e64"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("f789a3c1-3ac6-45bd-9277-458249206097"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("745be69a-a826-4681-afd6-fb078077e5bb"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("d5e44a76-0591-4d28-8a55-c4590a1c7cc6"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("5be60e33-7852-4448-ab98-34df4f167722"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("a00824d0-de14-4255-a2fd-b432239d0fd0"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("283a5f30-d476-4a1a-920e-3f88fdb244a9"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("ebded65c-08d4-499c-b40d-3aebd18ce3f9"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("d92f5e63-0235-42fe-beb4-d108f778e799"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("b9076b7e-ea7d-427d-8ea5-9ed2730642e2"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("36003e34-d4ee-4d69-9e17-69b75a912717"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("6bfe1e72-fb05-48a9-af9e-b64663e5bd0c"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("1d6d80d6-878a-4f3d-a24e-fc82a6b7a044"),
                            UserId = new Guid("d587f9bf-a06d-4fd3-99f7-e90d66a57d97")
                        },
                        new
                        {
                            PermissionId = new Guid("6f1153e0-a140-41b4-9430-f27b97b4755d"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("ffb242b0-6803-458a-b644-2af27bfcd628"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("3df86421-0c34-43b9-a68b-df2a0065462b"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("d13c1b7f-43d8-4242-8db1-5a5d8e8e088e"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("18382c9f-daa5-4277-a834-3705156ca653"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("e406e50c-23c0-4944-9ec1-aa060c8fa935"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("5e8e4361-74d0-4207-87d9-e2ca1b016fd4"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("3fbe914f-5dfb-4283-baef-ef8f2b8174a0"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("81cc5bdb-7ffb-4c76-9a6b-663d000a869e"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("df2a46d3-346f-4e08-b090-b7a81e3aa650"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("4d055f14-cf7a-40a5-b8ac-3c5f64b539b2"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("0f0baebe-81e1-4313-ad63-90bb0a7e8e64"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("f789a3c1-3ac6-45bd-9277-458249206097"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("745be69a-a826-4681-afd6-fb078077e5bb"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("d5e44a76-0591-4d28-8a55-c4590a1c7cc6"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("5be60e33-7852-4448-ab98-34df4f167722"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("a00824d0-de14-4255-a2fd-b432239d0fd0"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("283a5f30-d476-4a1a-920e-3f88fdb244a9"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("ebded65c-08d4-499c-b40d-3aebd18ce3f9"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("d92f5e63-0235-42fe-beb4-d108f778e799"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("b9076b7e-ea7d-427d-8ea5-9ed2730642e2"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("36003e34-d4ee-4d69-9e17-69b75a912717"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("6bfe1e72-fb05-48a9-af9e-b64663e5bd0c"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("1d6d80d6-878a-4f3d-a24e-fc82a6b7a044"),
                            UserId = new Guid("8dd082a4-4c26-46e3-920e-f096d407aed2")
                        },
                        new
                        {
                            PermissionId = new Guid("6f1153e0-a140-41b4-9430-f27b97b4755d"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("ffb242b0-6803-458a-b644-2af27bfcd628"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("3df86421-0c34-43b9-a68b-df2a0065462b"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("d13c1b7f-43d8-4242-8db1-5a5d8e8e088e"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("18382c9f-daa5-4277-a834-3705156ca653"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("e406e50c-23c0-4944-9ec1-aa060c8fa935"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("5e8e4361-74d0-4207-87d9-e2ca1b016fd4"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("3fbe914f-5dfb-4283-baef-ef8f2b8174a0"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("81cc5bdb-7ffb-4c76-9a6b-663d000a869e"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("df2a46d3-346f-4e08-b090-b7a81e3aa650"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("4d055f14-cf7a-40a5-b8ac-3c5f64b539b2"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("0f0baebe-81e1-4313-ad63-90bb0a7e8e64"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("f789a3c1-3ac6-45bd-9277-458249206097"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("745be69a-a826-4681-afd6-fb078077e5bb"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("d5e44a76-0591-4d28-8a55-c4590a1c7cc6"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("5be60e33-7852-4448-ab98-34df4f167722"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("a00824d0-de14-4255-a2fd-b432239d0fd0"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("283a5f30-d476-4a1a-920e-3f88fdb244a9"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("ebded65c-08d4-499c-b40d-3aebd18ce3f9"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("d92f5e63-0235-42fe-beb4-d108f778e799"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("b9076b7e-ea7d-427d-8ea5-9ed2730642e2"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("36003e34-d4ee-4d69-9e17-69b75a912717"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("6bfe1e72-fb05-48a9-af9e-b64663e5bd0c"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("1d6d80d6-878a-4f3d-a24e-fc82a6b7a044"),
                            UserId = new Guid("23489d17-5e4a-48fa-aa83-02c8dbd07b73")
                        },
                        new
                        {
                            PermissionId = new Guid("6f1153e0-a140-41b4-9430-f27b97b4755d"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("ffb242b0-6803-458a-b644-2af27bfcd628"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("3df86421-0c34-43b9-a68b-df2a0065462b"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("d13c1b7f-43d8-4242-8db1-5a5d8e8e088e"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("18382c9f-daa5-4277-a834-3705156ca653"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("e406e50c-23c0-4944-9ec1-aa060c8fa935"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("5e8e4361-74d0-4207-87d9-e2ca1b016fd4"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("3fbe914f-5dfb-4283-baef-ef8f2b8174a0"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("81cc5bdb-7ffb-4c76-9a6b-663d000a869e"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("df2a46d3-346f-4e08-b090-b7a81e3aa650"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("4d055f14-cf7a-40a5-b8ac-3c5f64b539b2"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("0f0baebe-81e1-4313-ad63-90bb0a7e8e64"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("f789a3c1-3ac6-45bd-9277-458249206097"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("745be69a-a826-4681-afd6-fb078077e5bb"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("d5e44a76-0591-4d28-8a55-c4590a1c7cc6"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("5be60e33-7852-4448-ab98-34df4f167722"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("a00824d0-de14-4255-a2fd-b432239d0fd0"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("283a5f30-d476-4a1a-920e-3f88fdb244a9"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("ebded65c-08d4-499c-b40d-3aebd18ce3f9"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("d92f5e63-0235-42fe-beb4-d108f778e799"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("b9076b7e-ea7d-427d-8ea5-9ed2730642e2"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("36003e34-d4ee-4d69-9e17-69b75a912717"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("6bfe1e72-fb05-48a9-af9e-b64663e5bd0c"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("1d6d80d6-878a-4f3d-a24e-fc82a6b7a044"),
                            UserId = new Guid("e5daa4f2-91e7-4f1b-ac05-d547b8fbf9c3")
                        },
                        new
                        {
                            PermissionId = new Guid("2797a995-92e9-4cc6-92a6-524cc8e37ad0"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("d7cb89bc-3824-48f3-89f7-6b13a822b1c8"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("3ec1778e-f770-4dfe-af78-81f8d888c013"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("21aa7240-2887-418d-bbd4-ebc65b268642"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("f1ec4f0d-1f30-4433-9742-8190339f60aa"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("ddd33fee-dc86-4451-bc25-1a5a6fa9837f"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("745be69a-a826-4681-afd6-fb078077e5bb"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("d5e44a76-0591-4d28-8a55-c4590a1c7cc6"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("5be60e33-7852-4448-ab98-34df4f167722"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("a00824d0-de14-4255-a2fd-b432239d0fd0"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("283a5f30-d476-4a1a-920e-3f88fdb244a9"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("ebded65c-08d4-499c-b40d-3aebd18ce3f9"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("d92f5e63-0235-42fe-beb4-d108f778e799"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("b9076b7e-ea7d-427d-8ea5-9ed2730642e2"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("36003e34-d4ee-4d69-9e17-69b75a912717"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("6bfe1e72-fb05-48a9-af9e-b64663e5bd0c"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("1d6d80d6-878a-4f3d-a24e-fc82a6b7a044"),
                            UserId = new Guid("3002d8cb-7e40-4294-949e-b92328370ea3")
                        },
                        new
                        {
                            PermissionId = new Guid("1cf5102a-a990-4897-a7a3-20e3a7a8a9c4"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("55d423b0-c045-42ec-b3d1-53059dd9a81f"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("f1861871-1dc0-48e8-b464-cc5414ec701c"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("3105272f-285f-4510-827d-68345265e5a4"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("2fbb8681-f44c-408a-9da9-83be613713eb"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("1bd3df79-28a6-43f5-86ba-88fbb26a3867"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("b4ff06ef-4ab5-4320-a328-34b102cf18b1"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("48ea25dc-0af9-4860-857e-618b566a38da"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("0ec09ab0-f4ee-4daf-a358-15e014327b12"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("d87de716-d773-41b7-850a-2e067b8058ea"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("afd88a6d-94e1-49db-8326-61f25425f751"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("745be69a-a826-4681-afd6-fb078077e5bb"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("d5e44a76-0591-4d28-8a55-c4590a1c7cc6"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("5be60e33-7852-4448-ab98-34df4f167722"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("a00824d0-de14-4255-a2fd-b432239d0fd0"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("283a5f30-d476-4a1a-920e-3f88fdb244a9"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("ebded65c-08d4-499c-b40d-3aebd18ce3f9"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("d92f5e63-0235-42fe-beb4-d108f778e799"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("b9076b7e-ea7d-427d-8ea5-9ed2730642e2"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("36003e34-d4ee-4d69-9e17-69b75a912717"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("6bfe1e72-fb05-48a9-af9e-b64663e5bd0c"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        },
                        new
                        {
                            PermissionId = new Guid("1d6d80d6-878a-4f3d-a24e-fc82a6b7a044"),
                            UserId = new Guid("8a137387-6a06-4a3e-a403-75be7de0e6a4")
                        });
                });

            modelBuilder.Entity("Domain.SecurityCam", b =>
                {
                    b.HasBaseType("Domain.Device");

                    b.Property<string>("CamSupportedActionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CamSupportedActionsJson");

                    b.Property<string>("UseTypeJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UseTypeJson");

                    b.HasDiscriminator().HasValue("SecurityCam");
                });

            modelBuilder.Entity("Domain.SmartLampHardware", b =>
                {
                    b.HasBaseType("Domain.Hardware");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("SmartLamp");
                });

            modelBuilder.Entity("Domain.WindowSensorHardware", b =>
                {
                    b.HasBaseType("Domain.Hardware");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("WindowSensor");
                });

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.HasOne("Domain.User", "Owner")
                        .WithOne()
                        .HasForeignKey("Domain.Company", "OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Device", b =>
                {
                    b.HasOne("Domain.Company", "Company")
                        .WithMany("Devices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Hardware", b =>
                {
                    b.HasOne("Domain.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Home", "Home")
                        .WithMany("Devices")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.HasOne("Domain.User", "Owner")
                        .WithMany("OwnedHomes")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.UbicationGeo", "Ubication", b1 =>
                        {
                            b1.Property<Guid>("HomeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Lat")
                                .HasColumnType("int");

                            b1.Property<int?>("Lon")
                                .HasColumnType("int");

                            b1.HasKey("HomeId");

                            b1.ToTable("Homes");

                            b1.WithOwner()
                                .HasForeignKey("HomeId");
                        });

                    b.Navigation("Owner");

                    b.Navigation("Ubication")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Notification", b =>
                {
                    b.HasOne("Domain.Hardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Hardware");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.NotificationMember", b =>
                {
                    b.HasOne("Domain.Home", "Home")
                        .WithMany("NotificationMembers")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.SessionUser", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.UserHomePermission", b =>
                {
                    b.HasOne("Domain.Home", "Home")
                        .WithMany("Members")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("HomePermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.UserPermissions", b =>
                {
                    b.HasOne("Domain.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Members");

                    b.Navigation("NotificationMembers");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("HomePermissions");

                    b.Navigation("OwnedHomes");
                });
#pragma warning restore 612, 618
        }
    }
}
