// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHub.DB;

#nullable disable

namespace SmartHub.DB.Migrations
{
    [DbContext(typeof(SmartHubAPIContext))]
    [Migration("20241119192413_HomeOwnerPermissionUpdateMigration")]
    partial class HomeOwnerPermissionUpdateMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Validator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Domain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotosJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Devices", (string)null);

                    b.HasDiscriminator<string>("DeviceType").HasValue("Device");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Hardware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HardwareType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Online")
                        .HasColumnType("bit");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("HomeId");

                    b.ToTable("Hardwares", (string)null);

                    b.HasDiscriminator<string>("HardwareType").HasValue("Hardware");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rooms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HardwareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HardwareId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Domain.NotificationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationMembers");
                });

            modelBuilder.Entity("Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7954b31f-bd0a-4130-a66e-db108c9634ab"),
                            Name = "getnotifications-notification"
                        },
                        new
                        {
                            Id = new Guid("fcb5e54b-fd12-486e-bebd-c6dcbee7d933"),
                            Name = "open-windowsensor"
                        },
                        new
                        {
                            Id = new Guid("775765c3-e0e0-4585-bfb6-1d019a007e2a"),
                            Name = "close-windowsensor"
                        },
                        new
                        {
                            Id = new Guid("7941e0c4-52b9-4d8f-b0fe-86abc45f10ba"),
                            Name = "motiondetection-camera"
                        },
                        new
                        {
                            Id = new Guid("32981713-ae9c-49c8-924d-6fa017f49734"),
                            Name = "persondetection-camera"
                        },
                        new
                        {
                            Id = new Guid("aa0d6bfd-0e96-41e3-a5f6-47f6a0f0a161"),
                            Name = "getdevices-devices"
                        },
                        new
                        {
                            Id = new Guid("4f5f0870-45e9-464e-b70c-6a5334adc9a9"),
                            Name = "getdevicetypes-devicetype"
                        },
                        new
                        {
                            Id = new Guid("29f06a8a-f868-4cd0-99bd-3d4f6775e4f1"),
                            Name = "motiondetection-motionsensor"
                        },
                        new
                        {
                            Id = new Guid("576fe3ab-f6eb-4324-ad6f-b08de29536da"),
                            Name = "on-smartlamp"
                        },
                        new
                        {
                            Id = new Guid("956df0d2-0f2a-4d6c-af89-ee8575c73a7e"),
                            Name = "off-smartlamp"
                        },
                        new
                        {
                            Id = new Guid("c1b8f116-ffdb-4acc-98c1-f3c9398d6338"),
                            Name = "getpermissions-home"
                        },
                        new
                        {
                            Id = new Guid("c406416b-55fc-4dd5-98d9-a91f2f175911"),
                            Name = "changeprofilephoto-user"
                        },
                        new
                        {
                            Id = new Guid("5dd1280a-ca32-4171-9b5b-be9abb256a49"),
                            Name = "createcompany-companies"
                        },
                        new
                        {
                            Id = new Guid("7bdd4ac0-f974-4b44-8c8a-57c43e86df14"),
                            Name = "addsensor-windowsensor"
                        },
                        new
                        {
                            Id = new Guid("52b315c5-f028-479b-9cd6-18d234638cee"),
                            Name = "addmotionsensor-motionsensor"
                        },
                        new
                        {
                            Id = new Guid("4684eb9b-d9ae-4034-b9d5-7b3f269e0bbc"),
                            Name = "addcamera-camera"
                        },
                        new
                        {
                            Id = new Guid("b87fe551-c466-4065-b15e-ea95dffda5d6"),
                            Name = "addhomeownerpermission-homeowner"
                        },
                        new
                        {
                            Id = new Guid("be8b9003-9f48-4059-9cc9-3854c4b8f262"),
                            Name = "addsmartlamp-smartlamp"
                        },
                        new
                        {
                            Id = new Guid("4cacaabe-0158-4ef8-8d59-1efbf552fd44"),
                            Name = "importdevices-devices"
                        },
                        new
                        {
                            Id = new Guid("9cba7fdc-b617-42d3-b155-ba8f6b7c1156"),
                            Name = "getimporters-devices"
                        },
                        new
                        {
                            Id = new Guid("4a7f937d-fe0a-4ce5-ad08-9feaae803bd6"),
                            Name = "getcompanyuser-companies"
                        },
                        new
                        {
                            Id = new Guid("15865c3a-02b0-43fb-9d71-467afb3d5c30"),
                            Name = "getdevicemodelvalidators-devices"
                        },
                        new
                        {
                            Id = new Guid("ce34c610-9033-4d53-8c93-97ff1fb573e4"),
                            Name = "selectdevicemodelvalidator-devices"
                        },
                        new
                        {
                            Id = new Guid("011768f8-e4be-4182-8b82-9502db9033a1"),
                            Name = "createadminaccount-administrator"
                        },
                        new
                        {
                            Id = new Guid("d12c03cc-46d5-4cd7-81bc-10bd8d80c5ce"),
                            Name = "deleteadminaccount-administrator"
                        },
                        new
                        {
                            Id = new Guid("5d4d3909-90e3-4bee-b1c6-cb1823473233"),
                            Name = "createcompanyowneraccount-companyowner"
                        },
                        new
                        {
                            Id = new Guid("40b2b972-de1c-4b02-850a-3424af1116d5"),
                            Name = "getaccounts-accounts"
                        },
                        new
                        {
                            Id = new Guid("6909f2a0-6697-46b3-8ed2-472bbdc208c7"),
                            Name = "getcompany-companies"
                        },
                        new
                        {
                            Id = new Guid("fceed037-1f24-456c-8d72-2e3591448d7f"),
                            Name = "addhomeownerpermission-homeowner"
                        },
                        new
                        {
                            Id = new Guid("9c56e718-5095-4229-8425-2ebb28db3e33"),
                            Name = "getrooms-home"
                        },
                        new
                        {
                            Id = new Guid("fb29d0e9-95c7-4a00-bece-95d07d2ed80a"),
                            Name = "add-home"
                        },
                        new
                        {
                            Id = new Guid("5b274e82-26ac-430c-adc5-1b0f94e37d7c"),
                            Name = "addmember-members"
                        },
                        new
                        {
                            Id = new Guid("c5aeb840-ed0e-42fb-a872-fb50e3cbd9ca"),
                            Name = "adddevice-home"
                        },
                        new
                        {
                            Id = new Guid("2a16f132-4948-4b65-bfe1-99803c9c6541"),
                            Name = "getmembers-members"
                        },
                        new
                        {
                            Id = new Guid("b0eeca35-2e40-4539-aa55-24dfb7489661"),
                            Name = "getdevices-home"
                        },
                        new
                        {
                            Id = new Guid("0b727d38-e3cf-457b-ae2d-f26e92c45c1a"),
                            Name = "addnotificationmembers-members"
                        },
                        new
                        {
                            Id = new Guid("f196825e-fd50-4385-ab38-286b5c910f7d"),
                            Name = "updatenamedevice-home"
                        },
                        new
                        {
                            Id = new Guid("4d9c49fc-b8d5-4821-b4d6-7a0b89b9905f"),
                            Name = "addmotionsensor-motionsensor"
                        },
                        new
                        {
                            Id = new Guid("445f0a35-0705-490c-b3dd-e229f8b1821f"),
                            Name = "gethomes-user"
                        },
                        new
                        {
                            Id = new Guid("654a8323-3ae2-4be7-915d-3b3c856bcb08"),
                            Name = "addpermission-members"
                        },
                        new
                        {
                            Id = new Guid("89b472f0-38dd-41e3-865a-478666d149f1"),
                            Name = "addrooms-home"
                        },
                        new
                        {
                            Id = new Guid("18ac9f5d-bb06-495b-ba97-3d4c613fce9e"),
                            Name = "updateroomdevice-home"
                        },
                        new
                        {
                            Id = new Guid("0d99f934-b3c0-4f3b-85f8-139be3381753"),
                            Name = "hardwareon-home"
                        },
                        new
                        {
                            Id = new Guid("345ffcfd-968e-449a-a77e-7e08e2363792"),
                            Name = "hardwareoff-home"
                        });
                });

            modelBuilder.Entity("Domain.SessionUser", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691"),
                            CreatedAt = new DateTime(2024, 11, 19, 16, 24, 13, 137, DateTimeKind.Local).AddTicks(6781),
                            Email = "rogerfederer@tennis.com",
                            Name = "Roger",
                            Password = "Federer@123",
                            ProfilePhoto = "federer.jpg",
                            Roles = "[0]",
                            Surname = "Federer"
                        },
                        new
                        {
                            Id = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5"),
                            CreatedAt = new DateTime(2024, 11, 19, 16, 24, 13, 137, DateTimeKind.Local).AddTicks(6830),
                            Email = "rafaelnadal@tennis.com",
                            Name = "Rafael",
                            Password = "Nadal@123",
                            ProfilePhoto = "nadal.jpg",
                            Roles = "[0]",
                            Surname = "Nadal"
                        },
                        new
                        {
                            Id = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7"),
                            CreatedAt = new DateTime(2024, 11, 19, 16, 24, 13, 137, DateTimeKind.Local).AddTicks(6834),
                            Email = "serenawilliams@tennis.com",
                            Name = "Serena",
                            Password = "Serena@123",
                            ProfilePhoto = "serena.jpg",
                            Roles = "[2]",
                            Surname = "Williams"
                        },
                        new
                        {
                            Id = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136"),
                            CreatedAt = new DateTime(2024, 11, 19, 16, 24, 13, 137, DateTimeKind.Local).AddTicks(6837),
                            Email = "novakdjokovic@tennis.com",
                            Name = "Novak",
                            Password = "Djokovic@123",
                            ProfilePhoto = "djokovic.jpg",
                            Roles = "[2,1]",
                            Surname = "Djokovic"
                        },
                        new
                        {
                            Id = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367"),
                            CreatedAt = new DateTime(2024, 11, 19, 16, 24, 13, 137, DateTimeKind.Local).AddTicks(6843),
                            Email = "steffigraf@tennis.com",
                            Name = "Steffi",
                            Password = "Steffi@123",
                            ProfilePhoto = "graf.jpg",
                            Roles = "[1]",
                            Surname = "Graf"
                        },
                        new
                        {
                            Id = new Guid("a59150be-53c9-4134-b5ac-5044e249f323"),
                            CreatedAt = new DateTime(2024, 11, 19, 16, 24, 13, 137, DateTimeKind.Local).AddTicks(6849),
                            Email = "andreagassi@tennis.com",
                            Name = "Andre",
                            Password = "Agassi@123",
                            ProfilePhoto = "agassi.jpg",
                            Roles = "[1]",
                            Surname = "Agassi"
                        },
                        new
                        {
                            Id = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff"),
                            CreatedAt = new DateTime(2024, 11, 19, 16, 24, 13, 137, DateTimeKind.Local).AddTicks(6858),
                            Email = "petesampras@tennis.com",
                            Name = "Pete",
                            Password = "Sampras@123",
                            ProfilePhoto = "sampras.jpg",
                            Roles = "[1]",
                            Surname = "Sampras"
                        },
                        new
                        {
                            Id = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868"),
                            CreatedAt = new DateTime(2024, 11, 19, 16, 24, 13, 137, DateTimeKind.Local).AddTicks(6866),
                            Email = "martinanavratilova@tennis.com",
                            Name = "Martina",
                            Password = "Navratilova@123",
                            ProfilePhoto = "navratilova.jpg",
                            Roles = "[1]",
                            Surname = "Navratilova"
                        },
                        new
                        {
                            Id = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8"),
                            CreatedAt = new DateTime(2024, 11, 19, 16, 24, 13, 137, DateTimeKind.Local).AddTicks(6869),
                            Email = "johnmcenroe@tennis.com",
                            Name = "John",
                            Password = "McEnroe@123",
                            ProfilePhoto = "mcenroe.jpg",
                            Roles = "[2]",
                            Surname = "McEnroe"
                        },
                        new
                        {
                            Id = new Guid("40720596-5246-4cf3-815a-77373be4fbe8"),
                            CreatedAt = new DateTime(2024, 11, 19, 16, 24, 13, 137, DateTimeKind.Local).AddTicks(6872),
                            Email = "billiejeanking@tennis.com",
                            Name = "Billie",
                            Password = "King@123",
                            ProfilePhoto = "king.jpg",
                            Roles = "[0]",
                            Surname = "Jean King"
                        });
                });

            modelBuilder.Entity("Domain.UserHomePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHomePermissions");
                });

            modelBuilder.Entity("Domain.UserPermissions", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionId = new Guid("5dd1280a-ca32-4171-9b5b-be9abb256a49"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("7bdd4ac0-f974-4b44-8c8a-57c43e86df14"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("52b315c5-f028-479b-9cd6-18d234638cee"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("4684eb9b-d9ae-4034-b9d5-7b3f269e0bbc"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("b87fe551-c466-4065-b15e-ea95dffda5d6"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("be8b9003-9f48-4059-9cc9-3854c4b8f262"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("4cacaabe-0158-4ef8-8d59-1efbf552fd44"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("9cba7fdc-b617-42d3-b155-ba8f6b7c1156"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("4a7f937d-fe0a-4ce5-ad08-9feaae803bd6"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("15865c3a-02b0-43fb-9d71-467afb3d5c30"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("ce34c610-9033-4d53-8c93-97ff1fb573e4"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("7954b31f-bd0a-4130-a66e-db108c9634ab"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("fcb5e54b-fd12-486e-bebd-c6dcbee7d933"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("775765c3-e0e0-4585-bfb6-1d019a007e2a"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("7941e0c4-52b9-4d8f-b0fe-86abc45f10ba"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("32981713-ae9c-49c8-924d-6fa017f49734"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("aa0d6bfd-0e96-41e3-a5f6-47f6a0f0a161"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("4f5f0870-45e9-464e-b70c-6a5334adc9a9"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("29f06a8a-f868-4cd0-99bd-3d4f6775e4f1"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("576fe3ab-f6eb-4324-ad6f-b08de29536da"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("956df0d2-0f2a-4d6c-af89-ee8575c73a7e"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("c1b8f116-ffdb-4acc-98c1-f3c9398d6338"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("c406416b-55fc-4dd5-98d9-a91f2f175911"),
                            UserId = new Guid("c2d7472d-3857-4e06-89ac-756cecc47691")
                        },
                        new
                        {
                            PermissionId = new Guid("5dd1280a-ca32-4171-9b5b-be9abb256a49"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("7bdd4ac0-f974-4b44-8c8a-57c43e86df14"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("52b315c5-f028-479b-9cd6-18d234638cee"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("4684eb9b-d9ae-4034-b9d5-7b3f269e0bbc"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("b87fe551-c466-4065-b15e-ea95dffda5d6"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("be8b9003-9f48-4059-9cc9-3854c4b8f262"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("4cacaabe-0158-4ef8-8d59-1efbf552fd44"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("9cba7fdc-b617-42d3-b155-ba8f6b7c1156"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("4a7f937d-fe0a-4ce5-ad08-9feaae803bd6"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("15865c3a-02b0-43fb-9d71-467afb3d5c30"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("ce34c610-9033-4d53-8c93-97ff1fb573e4"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("7954b31f-bd0a-4130-a66e-db108c9634ab"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("fcb5e54b-fd12-486e-bebd-c6dcbee7d933"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("775765c3-e0e0-4585-bfb6-1d019a007e2a"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("7941e0c4-52b9-4d8f-b0fe-86abc45f10ba"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("32981713-ae9c-49c8-924d-6fa017f49734"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("aa0d6bfd-0e96-41e3-a5f6-47f6a0f0a161"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("4f5f0870-45e9-464e-b70c-6a5334adc9a9"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("29f06a8a-f868-4cd0-99bd-3d4f6775e4f1"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("576fe3ab-f6eb-4324-ad6f-b08de29536da"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("956df0d2-0f2a-4d6c-af89-ee8575c73a7e"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("c1b8f116-ffdb-4acc-98c1-f3c9398d6338"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("c406416b-55fc-4dd5-98d9-a91f2f175911"),
                            UserId = new Guid("2d3a99ef-99cf-45b8-98da-89b6f559bcb5")
                        },
                        new
                        {
                            PermissionId = new Guid("011768f8-e4be-4182-8b82-9502db9033a1"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("d12c03cc-46d5-4cd7-81bc-10bd8d80c5ce"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("5d4d3909-90e3-4bee-b1c6-cb1823473233"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("40b2b972-de1c-4b02-850a-3424af1116d5"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("6909f2a0-6697-46b3-8ed2-472bbdc208c7"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("fceed037-1f24-456c-8d72-2e3591448d7f"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("7954b31f-bd0a-4130-a66e-db108c9634ab"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("fcb5e54b-fd12-486e-bebd-c6dcbee7d933"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("775765c3-e0e0-4585-bfb6-1d019a007e2a"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("7941e0c4-52b9-4d8f-b0fe-86abc45f10ba"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("32981713-ae9c-49c8-924d-6fa017f49734"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("aa0d6bfd-0e96-41e3-a5f6-47f6a0f0a161"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("4f5f0870-45e9-464e-b70c-6a5334adc9a9"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("29f06a8a-f868-4cd0-99bd-3d4f6775e4f1"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("576fe3ab-f6eb-4324-ad6f-b08de29536da"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("956df0d2-0f2a-4d6c-af89-ee8575c73a7e"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("c1b8f116-ffdb-4acc-98c1-f3c9398d6338"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("c406416b-55fc-4dd5-98d9-a91f2f175911"),
                            UserId = new Guid("23dcdf66-bb81-45bc-ad8b-c9ee3003c6e7")
                        },
                        new
                        {
                            PermissionId = new Guid("011768f8-e4be-4182-8b82-9502db9033a1"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("d12c03cc-46d5-4cd7-81bc-10bd8d80c5ce"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("5d4d3909-90e3-4bee-b1c6-cb1823473233"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("40b2b972-de1c-4b02-850a-3424af1116d5"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("6909f2a0-6697-46b3-8ed2-472bbdc208c7"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("fceed037-1f24-456c-8d72-2e3591448d7f"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("9c56e718-5095-4229-8425-2ebb28db3e33"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("fb29d0e9-95c7-4a00-bece-95d07d2ed80a"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("5b274e82-26ac-430c-adc5-1b0f94e37d7c"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("c5aeb840-ed0e-42fb-a872-fb50e3cbd9ca"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("2a16f132-4948-4b65-bfe1-99803c9c6541"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("b0eeca35-2e40-4539-aa55-24dfb7489661"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("0b727d38-e3cf-457b-ae2d-f26e92c45c1a"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("f196825e-fd50-4385-ab38-286b5c910f7d"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("4d9c49fc-b8d5-4821-b4d6-7a0b89b9905f"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("445f0a35-0705-490c-b3dd-e229f8b1821f"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("654a8323-3ae2-4be7-915d-3b3c856bcb08"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("89b472f0-38dd-41e3-865a-478666d149f1"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("18ac9f5d-bb06-495b-ba97-3d4c613fce9e"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("0d99f934-b3c0-4f3b-85f8-139be3381753"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("345ffcfd-968e-449a-a77e-7e08e2363792"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("7954b31f-bd0a-4130-a66e-db108c9634ab"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("fcb5e54b-fd12-486e-bebd-c6dcbee7d933"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("775765c3-e0e0-4585-bfb6-1d019a007e2a"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("7941e0c4-52b9-4d8f-b0fe-86abc45f10ba"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("32981713-ae9c-49c8-924d-6fa017f49734"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("aa0d6bfd-0e96-41e3-a5f6-47f6a0f0a161"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("4f5f0870-45e9-464e-b70c-6a5334adc9a9"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("29f06a8a-f868-4cd0-99bd-3d4f6775e4f1"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("576fe3ab-f6eb-4324-ad6f-b08de29536da"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("956df0d2-0f2a-4d6c-af89-ee8575c73a7e"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("c1b8f116-ffdb-4acc-98c1-f3c9398d6338"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("c406416b-55fc-4dd5-98d9-a91f2f175911"),
                            UserId = new Guid("9bb64b66-4b50-48ad-8721-c84df442c136")
                        },
                        new
                        {
                            PermissionId = new Guid("9c56e718-5095-4229-8425-2ebb28db3e33"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("fb29d0e9-95c7-4a00-bece-95d07d2ed80a"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("5b274e82-26ac-430c-adc5-1b0f94e37d7c"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("c5aeb840-ed0e-42fb-a872-fb50e3cbd9ca"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("2a16f132-4948-4b65-bfe1-99803c9c6541"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("b0eeca35-2e40-4539-aa55-24dfb7489661"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("0b727d38-e3cf-457b-ae2d-f26e92c45c1a"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("f196825e-fd50-4385-ab38-286b5c910f7d"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("4d9c49fc-b8d5-4821-b4d6-7a0b89b9905f"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("445f0a35-0705-490c-b3dd-e229f8b1821f"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("654a8323-3ae2-4be7-915d-3b3c856bcb08"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("89b472f0-38dd-41e3-865a-478666d149f1"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("18ac9f5d-bb06-495b-ba97-3d4c613fce9e"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("0d99f934-b3c0-4f3b-85f8-139be3381753"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("345ffcfd-968e-449a-a77e-7e08e2363792"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("7954b31f-bd0a-4130-a66e-db108c9634ab"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("fcb5e54b-fd12-486e-bebd-c6dcbee7d933"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("775765c3-e0e0-4585-bfb6-1d019a007e2a"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("7941e0c4-52b9-4d8f-b0fe-86abc45f10ba"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("32981713-ae9c-49c8-924d-6fa017f49734"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("aa0d6bfd-0e96-41e3-a5f6-47f6a0f0a161"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("4f5f0870-45e9-464e-b70c-6a5334adc9a9"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("29f06a8a-f868-4cd0-99bd-3d4f6775e4f1"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("576fe3ab-f6eb-4324-ad6f-b08de29536da"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("956df0d2-0f2a-4d6c-af89-ee8575c73a7e"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("c1b8f116-ffdb-4acc-98c1-f3c9398d6338"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("c406416b-55fc-4dd5-98d9-a91f2f175911"),
                            UserId = new Guid("88144533-c39d-4e05-8cb6-68a38b3ab367")
                        },
                        new
                        {
                            PermissionId = new Guid("9c56e718-5095-4229-8425-2ebb28db3e33"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("fb29d0e9-95c7-4a00-bece-95d07d2ed80a"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("5b274e82-26ac-430c-adc5-1b0f94e37d7c"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("c5aeb840-ed0e-42fb-a872-fb50e3cbd9ca"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("2a16f132-4948-4b65-bfe1-99803c9c6541"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("b0eeca35-2e40-4539-aa55-24dfb7489661"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("0b727d38-e3cf-457b-ae2d-f26e92c45c1a"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("f196825e-fd50-4385-ab38-286b5c910f7d"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("4d9c49fc-b8d5-4821-b4d6-7a0b89b9905f"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("445f0a35-0705-490c-b3dd-e229f8b1821f"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("654a8323-3ae2-4be7-915d-3b3c856bcb08"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("89b472f0-38dd-41e3-865a-478666d149f1"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("18ac9f5d-bb06-495b-ba97-3d4c613fce9e"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("0d99f934-b3c0-4f3b-85f8-139be3381753"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("345ffcfd-968e-449a-a77e-7e08e2363792"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("7954b31f-bd0a-4130-a66e-db108c9634ab"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("fcb5e54b-fd12-486e-bebd-c6dcbee7d933"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("775765c3-e0e0-4585-bfb6-1d019a007e2a"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("7941e0c4-52b9-4d8f-b0fe-86abc45f10ba"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("32981713-ae9c-49c8-924d-6fa017f49734"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("aa0d6bfd-0e96-41e3-a5f6-47f6a0f0a161"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("4f5f0870-45e9-464e-b70c-6a5334adc9a9"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("29f06a8a-f868-4cd0-99bd-3d4f6775e4f1"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("576fe3ab-f6eb-4324-ad6f-b08de29536da"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("956df0d2-0f2a-4d6c-af89-ee8575c73a7e"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("c1b8f116-ffdb-4acc-98c1-f3c9398d6338"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("c406416b-55fc-4dd5-98d9-a91f2f175911"),
                            UserId = new Guid("a59150be-53c9-4134-b5ac-5044e249f323")
                        },
                        new
                        {
                            PermissionId = new Guid("9c56e718-5095-4229-8425-2ebb28db3e33"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("fb29d0e9-95c7-4a00-bece-95d07d2ed80a"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("5b274e82-26ac-430c-adc5-1b0f94e37d7c"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("c5aeb840-ed0e-42fb-a872-fb50e3cbd9ca"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("2a16f132-4948-4b65-bfe1-99803c9c6541"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("b0eeca35-2e40-4539-aa55-24dfb7489661"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("0b727d38-e3cf-457b-ae2d-f26e92c45c1a"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("f196825e-fd50-4385-ab38-286b5c910f7d"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("4d9c49fc-b8d5-4821-b4d6-7a0b89b9905f"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("445f0a35-0705-490c-b3dd-e229f8b1821f"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("654a8323-3ae2-4be7-915d-3b3c856bcb08"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("89b472f0-38dd-41e3-865a-478666d149f1"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("18ac9f5d-bb06-495b-ba97-3d4c613fce9e"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("0d99f934-b3c0-4f3b-85f8-139be3381753"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("345ffcfd-968e-449a-a77e-7e08e2363792"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("7954b31f-bd0a-4130-a66e-db108c9634ab"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("fcb5e54b-fd12-486e-bebd-c6dcbee7d933"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("775765c3-e0e0-4585-bfb6-1d019a007e2a"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("7941e0c4-52b9-4d8f-b0fe-86abc45f10ba"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("32981713-ae9c-49c8-924d-6fa017f49734"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("aa0d6bfd-0e96-41e3-a5f6-47f6a0f0a161"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("4f5f0870-45e9-464e-b70c-6a5334adc9a9"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("29f06a8a-f868-4cd0-99bd-3d4f6775e4f1"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("576fe3ab-f6eb-4324-ad6f-b08de29536da"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("956df0d2-0f2a-4d6c-af89-ee8575c73a7e"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("c1b8f116-ffdb-4acc-98c1-f3c9398d6338"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("c406416b-55fc-4dd5-98d9-a91f2f175911"),
                            UserId = new Guid("d26f5a2b-e460-4c8f-ba55-551a4a4d38ff")
                        },
                        new
                        {
                            PermissionId = new Guid("9c56e718-5095-4229-8425-2ebb28db3e33"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("fb29d0e9-95c7-4a00-bece-95d07d2ed80a"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("5b274e82-26ac-430c-adc5-1b0f94e37d7c"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("c5aeb840-ed0e-42fb-a872-fb50e3cbd9ca"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("2a16f132-4948-4b65-bfe1-99803c9c6541"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("b0eeca35-2e40-4539-aa55-24dfb7489661"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("0b727d38-e3cf-457b-ae2d-f26e92c45c1a"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("f196825e-fd50-4385-ab38-286b5c910f7d"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("4d9c49fc-b8d5-4821-b4d6-7a0b89b9905f"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("445f0a35-0705-490c-b3dd-e229f8b1821f"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("654a8323-3ae2-4be7-915d-3b3c856bcb08"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("89b472f0-38dd-41e3-865a-478666d149f1"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("18ac9f5d-bb06-495b-ba97-3d4c613fce9e"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("0d99f934-b3c0-4f3b-85f8-139be3381753"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("345ffcfd-968e-449a-a77e-7e08e2363792"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("7954b31f-bd0a-4130-a66e-db108c9634ab"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("fcb5e54b-fd12-486e-bebd-c6dcbee7d933"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("775765c3-e0e0-4585-bfb6-1d019a007e2a"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("7941e0c4-52b9-4d8f-b0fe-86abc45f10ba"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("32981713-ae9c-49c8-924d-6fa017f49734"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("aa0d6bfd-0e96-41e3-a5f6-47f6a0f0a161"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("4f5f0870-45e9-464e-b70c-6a5334adc9a9"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("29f06a8a-f868-4cd0-99bd-3d4f6775e4f1"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("576fe3ab-f6eb-4324-ad6f-b08de29536da"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("956df0d2-0f2a-4d6c-af89-ee8575c73a7e"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("c1b8f116-ffdb-4acc-98c1-f3c9398d6338"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("c406416b-55fc-4dd5-98d9-a91f2f175911"),
                            UserId = new Guid("3188817e-0db9-4a36-8f2e-5891f2e30868")
                        },
                        new
                        {
                            PermissionId = new Guid("011768f8-e4be-4182-8b82-9502db9033a1"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("d12c03cc-46d5-4cd7-81bc-10bd8d80c5ce"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("5d4d3909-90e3-4bee-b1c6-cb1823473233"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("40b2b972-de1c-4b02-850a-3424af1116d5"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("6909f2a0-6697-46b3-8ed2-472bbdc208c7"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("fceed037-1f24-456c-8d72-2e3591448d7f"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("7954b31f-bd0a-4130-a66e-db108c9634ab"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("fcb5e54b-fd12-486e-bebd-c6dcbee7d933"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("775765c3-e0e0-4585-bfb6-1d019a007e2a"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("7941e0c4-52b9-4d8f-b0fe-86abc45f10ba"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("32981713-ae9c-49c8-924d-6fa017f49734"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("aa0d6bfd-0e96-41e3-a5f6-47f6a0f0a161"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("4f5f0870-45e9-464e-b70c-6a5334adc9a9"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("29f06a8a-f868-4cd0-99bd-3d4f6775e4f1"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("576fe3ab-f6eb-4324-ad6f-b08de29536da"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("956df0d2-0f2a-4d6c-af89-ee8575c73a7e"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("c1b8f116-ffdb-4acc-98c1-f3c9398d6338"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("c406416b-55fc-4dd5-98d9-a91f2f175911"),
                            UserId = new Guid("c58f351d-5651-467f-a227-706dff5cb5d8")
                        },
                        new
                        {
                            PermissionId = new Guid("5dd1280a-ca32-4171-9b5b-be9abb256a49"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("7bdd4ac0-f974-4b44-8c8a-57c43e86df14"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("52b315c5-f028-479b-9cd6-18d234638cee"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("4684eb9b-d9ae-4034-b9d5-7b3f269e0bbc"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("b87fe551-c466-4065-b15e-ea95dffda5d6"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("be8b9003-9f48-4059-9cc9-3854c4b8f262"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("4cacaabe-0158-4ef8-8d59-1efbf552fd44"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("9cba7fdc-b617-42d3-b155-ba8f6b7c1156"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("4a7f937d-fe0a-4ce5-ad08-9feaae803bd6"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("15865c3a-02b0-43fb-9d71-467afb3d5c30"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("ce34c610-9033-4d53-8c93-97ff1fb573e4"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("7954b31f-bd0a-4130-a66e-db108c9634ab"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("fcb5e54b-fd12-486e-bebd-c6dcbee7d933"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("775765c3-e0e0-4585-bfb6-1d019a007e2a"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("7941e0c4-52b9-4d8f-b0fe-86abc45f10ba"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("32981713-ae9c-49c8-924d-6fa017f49734"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("aa0d6bfd-0e96-41e3-a5f6-47f6a0f0a161"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("4f5f0870-45e9-464e-b70c-6a5334adc9a9"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("29f06a8a-f868-4cd0-99bd-3d4f6775e4f1"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("576fe3ab-f6eb-4324-ad6f-b08de29536da"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("956df0d2-0f2a-4d6c-af89-ee8575c73a7e"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("c1b8f116-ffdb-4acc-98c1-f3c9398d6338"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        },
                        new
                        {
                            PermissionId = new Guid("c406416b-55fc-4dd5-98d9-a91f2f175911"),
                            UserId = new Guid("40720596-5246-4cf3-815a-77373be4fbe8")
                        });
                });

            modelBuilder.Entity("Domain.SecurityCam", b =>
                {
                    b.HasBaseType("Domain.Device");

                    b.Property<string>("CamSupportedActionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CamSupportedActionsJson");

                    b.Property<string>("UseTypeJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UseTypeJson");

                    b.HasDiscriminator().HasValue("SecurityCam");
                });

            modelBuilder.Entity("Domain.SmartLampHardware", b =>
                {
                    b.HasBaseType("Domain.Hardware");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("SmartLamp");
                });

            modelBuilder.Entity("Domain.WindowSensorHardware", b =>
                {
                    b.HasBaseType("Domain.Hardware");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("WindowSensor");
                });

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.HasOne("Domain.User", "Owner")
                        .WithOne()
                        .HasForeignKey("Domain.Company", "OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Device", b =>
                {
                    b.HasOne("Domain.Company", "Company")
                        .WithMany("Devices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Hardware", b =>
                {
                    b.HasOne("Domain.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Home", "Home")
                        .WithMany("Devices")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.HasOne("Domain.User", "Owner")
                        .WithMany("OwnedHomes")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.UbicationGeo", "Ubication", b1 =>
                        {
                            b1.Property<Guid>("HomeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Lat")
                                .HasColumnType("int");

                            b1.Property<int?>("Lon")
                                .HasColumnType("int");

                            b1.HasKey("HomeId");

                            b1.ToTable("Homes");

                            b1.WithOwner()
                                .HasForeignKey("HomeId");
                        });

                    b.Navigation("Owner");

                    b.Navigation("Ubication")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Notification", b =>
                {
                    b.HasOne("Domain.Hardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Hardware");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.NotificationMember", b =>
                {
                    b.HasOne("Domain.Home", "Home")
                        .WithMany("NotificationMembers")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.SessionUser", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.UserHomePermission", b =>
                {
                    b.HasOne("Domain.Home", "Home")
                        .WithMany("Members")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("HomePermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.UserPermissions", b =>
                {
                    b.HasOne("Domain.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Members");

                    b.Navigation("NotificationMembers");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("HomePermissions");

                    b.Navigation("OwnedHomes");
                });
#pragma warning restore 612, 618
        }
    }
}
