// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHub.DB;

#nullable disable

namespace SmartHub.DB.Migrations
{
    [DbContext(typeof(SmartHubAPIContext))]
    [Migration("20241117034949_CompanyOwnerPerimssionsMigration")]
    partial class CompanyOwnerPerimssionsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Domain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotosJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Devices", (string)null);

                    b.HasDiscriminator<string>("DeviceType").HasValue("Device");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Hardware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HardwareType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Online")
                        .HasColumnType("bit");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("HomeId");

                    b.ToTable("Hardwares", (string)null);

                    b.HasDiscriminator<string>("HardwareType").HasValue("Hardware");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rooms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HardwareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HardwareId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Domain.NotificationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationMembers");
                });

            modelBuilder.Entity("Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa44e395-8089-478b-9b17-e3aedeb5f887"),
                            Name = "getnotifications-notification"
                        },
                        new
                        {
                            Id = new Guid("a02296dc-9392-4ef9-9e3d-5af8e889cc7c"),
                            Name = "open-windowsensor"
                        },
                        new
                        {
                            Id = new Guid("4285bf3b-2150-4c7d-bde0-2ae392f8c4e8"),
                            Name = "close-windowsensor"
                        },
                        new
                        {
                            Id = new Guid("8b401275-21e7-4e67-ac64-98fe95d52fb0"),
                            Name = "motiondetection-camera"
                        },
                        new
                        {
                            Id = new Guid("0e7edc7b-9688-4f76-a0f7-3baba00dd077"),
                            Name = "persondetection-camera"
                        },
                        new
                        {
                            Id = new Guid("f34af2b3-5e49-4183-95a5-05821cdcb820"),
                            Name = "getdevices-devices"
                        },
                        new
                        {
                            Id = new Guid("f75fc379-eb23-49ad-a60e-0b4e0556e7eb"),
                            Name = "getdevicetypes-devicetype"
                        },
                        new
                        {
                            Id = new Guid("05180053-fa51-4263-b26c-c8eb55d0cc2f"),
                            Name = "motiondetection-motionsensor"
                        },
                        new
                        {
                            Id = new Guid("ad915dfa-0463-4b42-8e33-11b4539f519c"),
                            Name = "on-smartlamp"
                        },
                        new
                        {
                            Id = new Guid("b31418a4-070d-42c8-841e-5aa4de008184"),
                            Name = "off-smartlamp"
                        },
                        new
                        {
                            Id = new Guid("34706640-abae-4206-b395-8688da213ee4"),
                            Name = "getpermissions-home"
                        },
                        new
                        {
                            Id = new Guid("07e8ff14-1ce0-457d-970c-69c745eb574e"),
                            Name = "createcompany-companies"
                        },
                        new
                        {
                            Id = new Guid("01d254b7-37a9-4693-903d-405bfd06eeb2"),
                            Name = "addsensor-windowsensor"
                        },
                        new
                        {
                            Id = new Guid("4e784112-5544-4879-98db-8daaf9082135"),
                            Name = "addmotionsensor-motionsensor"
                        },
                        new
                        {
                            Id = new Guid("123192d4-318e-4395-8bfe-fc8ac1e5f6c7"),
                            Name = "addcamera-camera"
                        },
                        new
                        {
                            Id = new Guid("25a95351-ac71-4b27-b4a5-ffd76b355d5c"),
                            Name = "addhomeownerpermission-homeowner"
                        },
                        new
                        {
                            Id = new Guid("31fa3476-ffea-408c-8d11-0e345d9e6e9b"),
                            Name = "addsmartlamp-smartlamp"
                        },
                        new
                        {
                            Id = new Guid("966e3761-9e30-4975-9902-7d6d81fc0e54"),
                            Name = "importdevices-devices"
                        },
                        new
                        {
                            Id = new Guid("997ac669-bcd1-4d3c-b38a-1c3050a774bf"),
                            Name = "getimporters-devices"
                        },
                        new
                        {
                            Id = new Guid("6c074926-8c66-4cbc-8693-b04e64a4ca70"),
                            Name = "getcompanyuser-companies"
                        },
                        new
                        {
                            Id = new Guid("c8e9702e-5185-4bda-8ac6-a394171ddb40"),
                            Name = "createadminaccount-administrator"
                        },
                        new
                        {
                            Id = new Guid("4f332726-7b86-48f4-b3fe-a9ab53057d12"),
                            Name = "deleteadminaccount-administrator"
                        },
                        new
                        {
                            Id = new Guid("75e3a6ec-2c71-4cdb-b5b6-27e13e78f8f7"),
                            Name = "createcompanyowneraccount-companyowner"
                        },
                        new
                        {
                            Id = new Guid("46442ca2-3775-49b9-af9e-3794214a71e0"),
                            Name = "getaccounts-accounts"
                        },
                        new
                        {
                            Id = new Guid("9632c2ef-79a4-45e1-90db-064855fd4eee"),
                            Name = "getcompany-companies"
                        },
                        new
                        {
                            Id = new Guid("708eebc6-8f17-4fe5-ae66-c3846e09b182"),
                            Name = "addhomeownerpermission-homeowner"
                        },
                        new
                        {
                            Id = new Guid("7ce918b9-9751-4649-a532-923a2fe8e58b"),
                            Name = "getrooms-home"
                        },
                        new
                        {
                            Id = new Guid("605daf83-93e6-4742-bcbf-4515107a66b5"),
                            Name = "newhome-home"
                        },
                        new
                        {
                            Id = new Guid("f97ac710-1562-436d-8ea5-a21da10e372a"),
                            Name = "addmember-members"
                        },
                        new
                        {
                            Id = new Guid("f8800c36-2e0b-4862-9db2-3f230c19515b"),
                            Name = "adddevice-home"
                        },
                        new
                        {
                            Id = new Guid("09f8a3de-43f3-42e4-99c5-09b1fb91b24c"),
                            Name = "getmembers-members"
                        },
                        new
                        {
                            Id = new Guid("a8a546a2-fc19-4496-8f71-7fe2477538bf"),
                            Name = "getdevices-home"
                        },
                        new
                        {
                            Id = new Guid("5fff3ba2-9f13-4550-956e-1419b425c3a9"),
                            Name = "addnotificationmembers-members"
                        },
                        new
                        {
                            Id = new Guid("d3f4d967-1368-473b-bcee-cedd83518b8c"),
                            Name = "updatenamedevice-home"
                        },
                        new
                        {
                            Id = new Guid("18d90191-4dac-4b79-a2b2-4ca4a910c20b"),
                            Name = "addmotionsensor-motionsensor"
                        },
                        new
                        {
                            Id = new Guid("a9c7f68d-80b7-4c26-98a3-a1237d3a74be"),
                            Name = "gethomes-user"
                        },
                        new
                        {
                            Id = new Guid("8314e7a1-9725-4b08-be40-26614781e77f"),
                            Name = "addpermission-members"
                        },
                        new
                        {
                            Id = new Guid("d8209c2d-6779-4ce7-b7ff-e0585631a004"),
                            Name = "addrooms-home"
                        },
                        new
                        {
                            Id = new Guid("ce7ff9d8-5936-4c7c-9ba5-c65689bebf05"),
                            Name = "updateroomdevice-home"
                        });
                });

            modelBuilder.Entity("Domain.SessionUser", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8"),
                            CreatedAt = new DateTime(2024, 11, 17, 0, 49, 48, 680, DateTimeKind.Local).AddTicks(6340),
                            Email = "rogerfederer@tennis.com",
                            Name = "Roger",
                            Password = "Federer@123",
                            ProfilePhoto = "federer.jpg",
                            Roles = "[0]",
                            Surname = "Federer"
                        },
                        new
                        {
                            Id = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e"),
                            CreatedAt = new DateTime(2024, 11, 17, 0, 49, 48, 680, DateTimeKind.Local).AddTicks(6363),
                            Email = "rafaelnadal@tennis.com",
                            Name = "Rafael",
                            Password = "Nadal@123",
                            ProfilePhoto = "nadal.jpg",
                            Roles = "[0]",
                            Surname = "Nadal"
                        },
                        new
                        {
                            Id = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69"),
                            CreatedAt = new DateTime(2024, 11, 17, 0, 49, 48, 680, DateTimeKind.Local).AddTicks(6368),
                            Email = "serenawilliams@tennis.com",
                            Name = "Serena",
                            Password = "Serena@123",
                            ProfilePhoto = "serena.jpg",
                            Roles = "[2]",
                            Surname = "Williams"
                        },
                        new
                        {
                            Id = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f"),
                            CreatedAt = new DateTime(2024, 11, 17, 0, 49, 48, 680, DateTimeKind.Local).AddTicks(6371),
                            Email = "novakdjokovic@tennis.com",
                            Name = "Novak",
                            Password = "Djokovic@123",
                            ProfilePhoto = "djokovic.jpg",
                            Roles = "[2,1]",
                            Surname = "Djokovic"
                        },
                        new
                        {
                            Id = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab"),
                            CreatedAt = new DateTime(2024, 11, 17, 0, 49, 48, 680, DateTimeKind.Local).AddTicks(6374),
                            Email = "steffigraf@tennis.com",
                            Name = "Steffi",
                            Password = "Steffi@123",
                            ProfilePhoto = "graf.jpg",
                            Roles = "[1]",
                            Surname = "Graf"
                        },
                        new
                        {
                            Id = new Guid("fa960763-b8e2-4fff-957b-61af6be52815"),
                            CreatedAt = new DateTime(2024, 11, 17, 0, 49, 48, 680, DateTimeKind.Local).AddTicks(6377),
                            Email = "andreagassi@tennis.com",
                            Name = "Andre",
                            Password = "Agassi@123",
                            ProfilePhoto = "agassi.jpg",
                            Roles = "[1]",
                            Surname = "Agassi"
                        },
                        new
                        {
                            Id = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5"),
                            CreatedAt = new DateTime(2024, 11, 17, 0, 49, 48, 680, DateTimeKind.Local).AddTicks(6380),
                            Email = "petesampras@tennis.com",
                            Name = "Pete",
                            Password = "Sampras@123",
                            ProfilePhoto = "sampras.jpg",
                            Roles = "[1]",
                            Surname = "Sampras"
                        },
                        new
                        {
                            Id = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301"),
                            CreatedAt = new DateTime(2024, 11, 17, 0, 49, 48, 680, DateTimeKind.Local).AddTicks(6382),
                            Email = "martinanavratilova@tennis.com",
                            Name = "Martina",
                            Password = "Navratilova@123",
                            ProfilePhoto = "navratilova.jpg",
                            Roles = "[1]",
                            Surname = "Navratilova"
                        },
                        new
                        {
                            Id = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2"),
                            CreatedAt = new DateTime(2024, 11, 17, 0, 49, 48, 680, DateTimeKind.Local).AddTicks(6386),
                            Email = "johnmcenroe@tennis.com",
                            Name = "John",
                            Password = "McEnroe@123",
                            ProfilePhoto = "mcenroe.jpg",
                            Roles = "[2]",
                            Surname = "McEnroe"
                        },
                        new
                        {
                            Id = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01"),
                            CreatedAt = new DateTime(2024, 11, 17, 0, 49, 48, 680, DateTimeKind.Local).AddTicks(6390),
                            Email = "billiejeanking@tennis.com",
                            Name = "Billie",
                            Password = "King@123",
                            ProfilePhoto = "king.jpg",
                            Roles = "[0]",
                            Surname = "Jean King"
                        });
                });

            modelBuilder.Entity("Domain.UserHomePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHomePermissions");
                });

            modelBuilder.Entity("Domain.UserPermissions", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionId = new Guid("07e8ff14-1ce0-457d-970c-69c745eb574e"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("01d254b7-37a9-4693-903d-405bfd06eeb2"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("4e784112-5544-4879-98db-8daaf9082135"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("123192d4-318e-4395-8bfe-fc8ac1e5f6c7"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("25a95351-ac71-4b27-b4a5-ffd76b355d5c"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("31fa3476-ffea-408c-8d11-0e345d9e6e9b"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("966e3761-9e30-4975-9902-7d6d81fc0e54"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("997ac669-bcd1-4d3c-b38a-1c3050a774bf"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("6c074926-8c66-4cbc-8693-b04e64a4ca70"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("aa44e395-8089-478b-9b17-e3aedeb5f887"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("a02296dc-9392-4ef9-9e3d-5af8e889cc7c"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("4285bf3b-2150-4c7d-bde0-2ae392f8c4e8"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("8b401275-21e7-4e67-ac64-98fe95d52fb0"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("0e7edc7b-9688-4f76-a0f7-3baba00dd077"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("f34af2b3-5e49-4183-95a5-05821cdcb820"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("f75fc379-eb23-49ad-a60e-0b4e0556e7eb"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("05180053-fa51-4263-b26c-c8eb55d0cc2f"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("ad915dfa-0463-4b42-8e33-11b4539f519c"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("b31418a4-070d-42c8-841e-5aa4de008184"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("34706640-abae-4206-b395-8688da213ee4"),
                            UserId = new Guid("032766bb-f502-4422-a235-8c051ad7bbd8")
                        },
                        new
                        {
                            PermissionId = new Guid("07e8ff14-1ce0-457d-970c-69c745eb574e"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("01d254b7-37a9-4693-903d-405bfd06eeb2"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("4e784112-5544-4879-98db-8daaf9082135"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("123192d4-318e-4395-8bfe-fc8ac1e5f6c7"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("25a95351-ac71-4b27-b4a5-ffd76b355d5c"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("31fa3476-ffea-408c-8d11-0e345d9e6e9b"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("966e3761-9e30-4975-9902-7d6d81fc0e54"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("997ac669-bcd1-4d3c-b38a-1c3050a774bf"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("6c074926-8c66-4cbc-8693-b04e64a4ca70"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("aa44e395-8089-478b-9b17-e3aedeb5f887"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("a02296dc-9392-4ef9-9e3d-5af8e889cc7c"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("4285bf3b-2150-4c7d-bde0-2ae392f8c4e8"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("8b401275-21e7-4e67-ac64-98fe95d52fb0"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("0e7edc7b-9688-4f76-a0f7-3baba00dd077"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("f34af2b3-5e49-4183-95a5-05821cdcb820"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("f75fc379-eb23-49ad-a60e-0b4e0556e7eb"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("05180053-fa51-4263-b26c-c8eb55d0cc2f"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("ad915dfa-0463-4b42-8e33-11b4539f519c"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("b31418a4-070d-42c8-841e-5aa4de008184"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("34706640-abae-4206-b395-8688da213ee4"),
                            UserId = new Guid("1ed8ae8f-9718-41d9-a4fd-6e8014a60b8e")
                        },
                        new
                        {
                            PermissionId = new Guid("c8e9702e-5185-4bda-8ac6-a394171ddb40"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("4f332726-7b86-48f4-b3fe-a9ab53057d12"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("75e3a6ec-2c71-4cdb-b5b6-27e13e78f8f7"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("46442ca2-3775-49b9-af9e-3794214a71e0"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("9632c2ef-79a4-45e1-90db-064855fd4eee"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("708eebc6-8f17-4fe5-ae66-c3846e09b182"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("aa44e395-8089-478b-9b17-e3aedeb5f887"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("a02296dc-9392-4ef9-9e3d-5af8e889cc7c"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("4285bf3b-2150-4c7d-bde0-2ae392f8c4e8"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("8b401275-21e7-4e67-ac64-98fe95d52fb0"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("0e7edc7b-9688-4f76-a0f7-3baba00dd077"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("f34af2b3-5e49-4183-95a5-05821cdcb820"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("f75fc379-eb23-49ad-a60e-0b4e0556e7eb"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("05180053-fa51-4263-b26c-c8eb55d0cc2f"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("ad915dfa-0463-4b42-8e33-11b4539f519c"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("b31418a4-070d-42c8-841e-5aa4de008184"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("34706640-abae-4206-b395-8688da213ee4"),
                            UserId = new Guid("8f114abd-8fdb-4983-8859-b242d7439e69")
                        },
                        new
                        {
                            PermissionId = new Guid("c8e9702e-5185-4bda-8ac6-a394171ddb40"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("4f332726-7b86-48f4-b3fe-a9ab53057d12"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("75e3a6ec-2c71-4cdb-b5b6-27e13e78f8f7"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("46442ca2-3775-49b9-af9e-3794214a71e0"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("9632c2ef-79a4-45e1-90db-064855fd4eee"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("708eebc6-8f17-4fe5-ae66-c3846e09b182"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("7ce918b9-9751-4649-a532-923a2fe8e58b"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("605daf83-93e6-4742-bcbf-4515107a66b5"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("f97ac710-1562-436d-8ea5-a21da10e372a"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("f8800c36-2e0b-4862-9db2-3f230c19515b"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("09f8a3de-43f3-42e4-99c5-09b1fb91b24c"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("a8a546a2-fc19-4496-8f71-7fe2477538bf"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("5fff3ba2-9f13-4550-956e-1419b425c3a9"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("d3f4d967-1368-473b-bcee-cedd83518b8c"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("18d90191-4dac-4b79-a2b2-4ca4a910c20b"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("a9c7f68d-80b7-4c26-98a3-a1237d3a74be"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("8314e7a1-9725-4b08-be40-26614781e77f"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("d8209c2d-6779-4ce7-b7ff-e0585631a004"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("ce7ff9d8-5936-4c7c-9ba5-c65689bebf05"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("aa44e395-8089-478b-9b17-e3aedeb5f887"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("a02296dc-9392-4ef9-9e3d-5af8e889cc7c"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("4285bf3b-2150-4c7d-bde0-2ae392f8c4e8"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("8b401275-21e7-4e67-ac64-98fe95d52fb0"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("0e7edc7b-9688-4f76-a0f7-3baba00dd077"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("f34af2b3-5e49-4183-95a5-05821cdcb820"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("f75fc379-eb23-49ad-a60e-0b4e0556e7eb"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("05180053-fa51-4263-b26c-c8eb55d0cc2f"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("ad915dfa-0463-4b42-8e33-11b4539f519c"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("b31418a4-070d-42c8-841e-5aa4de008184"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("34706640-abae-4206-b395-8688da213ee4"),
                            UserId = new Guid("70bd4bf5-c9a1-4dcb-85dd-11dcb2ada27f")
                        },
                        new
                        {
                            PermissionId = new Guid("7ce918b9-9751-4649-a532-923a2fe8e58b"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("605daf83-93e6-4742-bcbf-4515107a66b5"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("f97ac710-1562-436d-8ea5-a21da10e372a"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("f8800c36-2e0b-4862-9db2-3f230c19515b"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("09f8a3de-43f3-42e4-99c5-09b1fb91b24c"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("a8a546a2-fc19-4496-8f71-7fe2477538bf"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("5fff3ba2-9f13-4550-956e-1419b425c3a9"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("d3f4d967-1368-473b-bcee-cedd83518b8c"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("18d90191-4dac-4b79-a2b2-4ca4a910c20b"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("a9c7f68d-80b7-4c26-98a3-a1237d3a74be"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("8314e7a1-9725-4b08-be40-26614781e77f"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("d8209c2d-6779-4ce7-b7ff-e0585631a004"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("ce7ff9d8-5936-4c7c-9ba5-c65689bebf05"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("aa44e395-8089-478b-9b17-e3aedeb5f887"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("a02296dc-9392-4ef9-9e3d-5af8e889cc7c"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("4285bf3b-2150-4c7d-bde0-2ae392f8c4e8"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("8b401275-21e7-4e67-ac64-98fe95d52fb0"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("0e7edc7b-9688-4f76-a0f7-3baba00dd077"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("f34af2b3-5e49-4183-95a5-05821cdcb820"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("f75fc379-eb23-49ad-a60e-0b4e0556e7eb"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("05180053-fa51-4263-b26c-c8eb55d0cc2f"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("ad915dfa-0463-4b42-8e33-11b4539f519c"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("b31418a4-070d-42c8-841e-5aa4de008184"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("34706640-abae-4206-b395-8688da213ee4"),
                            UserId = new Guid("7a404ea5-d485-480b-bbea-0961ab6414ab")
                        },
                        new
                        {
                            PermissionId = new Guid("7ce918b9-9751-4649-a532-923a2fe8e58b"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("605daf83-93e6-4742-bcbf-4515107a66b5"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("f97ac710-1562-436d-8ea5-a21da10e372a"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("f8800c36-2e0b-4862-9db2-3f230c19515b"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("09f8a3de-43f3-42e4-99c5-09b1fb91b24c"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("a8a546a2-fc19-4496-8f71-7fe2477538bf"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("5fff3ba2-9f13-4550-956e-1419b425c3a9"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("d3f4d967-1368-473b-bcee-cedd83518b8c"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("18d90191-4dac-4b79-a2b2-4ca4a910c20b"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("a9c7f68d-80b7-4c26-98a3-a1237d3a74be"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("8314e7a1-9725-4b08-be40-26614781e77f"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("d8209c2d-6779-4ce7-b7ff-e0585631a004"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("ce7ff9d8-5936-4c7c-9ba5-c65689bebf05"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("aa44e395-8089-478b-9b17-e3aedeb5f887"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("a02296dc-9392-4ef9-9e3d-5af8e889cc7c"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("4285bf3b-2150-4c7d-bde0-2ae392f8c4e8"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("8b401275-21e7-4e67-ac64-98fe95d52fb0"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("0e7edc7b-9688-4f76-a0f7-3baba00dd077"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("f34af2b3-5e49-4183-95a5-05821cdcb820"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("f75fc379-eb23-49ad-a60e-0b4e0556e7eb"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("05180053-fa51-4263-b26c-c8eb55d0cc2f"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("ad915dfa-0463-4b42-8e33-11b4539f519c"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("b31418a4-070d-42c8-841e-5aa4de008184"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("34706640-abae-4206-b395-8688da213ee4"),
                            UserId = new Guid("fa960763-b8e2-4fff-957b-61af6be52815")
                        },
                        new
                        {
                            PermissionId = new Guid("7ce918b9-9751-4649-a532-923a2fe8e58b"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("605daf83-93e6-4742-bcbf-4515107a66b5"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("f97ac710-1562-436d-8ea5-a21da10e372a"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("f8800c36-2e0b-4862-9db2-3f230c19515b"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("09f8a3de-43f3-42e4-99c5-09b1fb91b24c"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("a8a546a2-fc19-4496-8f71-7fe2477538bf"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("5fff3ba2-9f13-4550-956e-1419b425c3a9"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("d3f4d967-1368-473b-bcee-cedd83518b8c"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("18d90191-4dac-4b79-a2b2-4ca4a910c20b"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("a9c7f68d-80b7-4c26-98a3-a1237d3a74be"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("8314e7a1-9725-4b08-be40-26614781e77f"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("d8209c2d-6779-4ce7-b7ff-e0585631a004"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("ce7ff9d8-5936-4c7c-9ba5-c65689bebf05"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("aa44e395-8089-478b-9b17-e3aedeb5f887"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("a02296dc-9392-4ef9-9e3d-5af8e889cc7c"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("4285bf3b-2150-4c7d-bde0-2ae392f8c4e8"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("8b401275-21e7-4e67-ac64-98fe95d52fb0"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("0e7edc7b-9688-4f76-a0f7-3baba00dd077"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("f34af2b3-5e49-4183-95a5-05821cdcb820"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("f75fc379-eb23-49ad-a60e-0b4e0556e7eb"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("05180053-fa51-4263-b26c-c8eb55d0cc2f"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("ad915dfa-0463-4b42-8e33-11b4539f519c"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("b31418a4-070d-42c8-841e-5aa4de008184"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("34706640-abae-4206-b395-8688da213ee4"),
                            UserId = new Guid("23ca9092-230b-47ef-a511-6d47b8c6aaa5")
                        },
                        new
                        {
                            PermissionId = new Guid("7ce918b9-9751-4649-a532-923a2fe8e58b"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("605daf83-93e6-4742-bcbf-4515107a66b5"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("f97ac710-1562-436d-8ea5-a21da10e372a"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("f8800c36-2e0b-4862-9db2-3f230c19515b"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("09f8a3de-43f3-42e4-99c5-09b1fb91b24c"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("a8a546a2-fc19-4496-8f71-7fe2477538bf"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("5fff3ba2-9f13-4550-956e-1419b425c3a9"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("d3f4d967-1368-473b-bcee-cedd83518b8c"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("18d90191-4dac-4b79-a2b2-4ca4a910c20b"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("a9c7f68d-80b7-4c26-98a3-a1237d3a74be"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("8314e7a1-9725-4b08-be40-26614781e77f"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("d8209c2d-6779-4ce7-b7ff-e0585631a004"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("ce7ff9d8-5936-4c7c-9ba5-c65689bebf05"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("aa44e395-8089-478b-9b17-e3aedeb5f887"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("a02296dc-9392-4ef9-9e3d-5af8e889cc7c"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("4285bf3b-2150-4c7d-bde0-2ae392f8c4e8"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("8b401275-21e7-4e67-ac64-98fe95d52fb0"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("0e7edc7b-9688-4f76-a0f7-3baba00dd077"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("f34af2b3-5e49-4183-95a5-05821cdcb820"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("f75fc379-eb23-49ad-a60e-0b4e0556e7eb"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("05180053-fa51-4263-b26c-c8eb55d0cc2f"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("ad915dfa-0463-4b42-8e33-11b4539f519c"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("b31418a4-070d-42c8-841e-5aa4de008184"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("34706640-abae-4206-b395-8688da213ee4"),
                            UserId = new Guid("b56be067-cb35-4fd0-8f65-2f0a80d96301")
                        },
                        new
                        {
                            PermissionId = new Guid("c8e9702e-5185-4bda-8ac6-a394171ddb40"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("4f332726-7b86-48f4-b3fe-a9ab53057d12"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("75e3a6ec-2c71-4cdb-b5b6-27e13e78f8f7"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("46442ca2-3775-49b9-af9e-3794214a71e0"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("9632c2ef-79a4-45e1-90db-064855fd4eee"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("708eebc6-8f17-4fe5-ae66-c3846e09b182"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("aa44e395-8089-478b-9b17-e3aedeb5f887"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("a02296dc-9392-4ef9-9e3d-5af8e889cc7c"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("4285bf3b-2150-4c7d-bde0-2ae392f8c4e8"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("8b401275-21e7-4e67-ac64-98fe95d52fb0"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("0e7edc7b-9688-4f76-a0f7-3baba00dd077"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("f34af2b3-5e49-4183-95a5-05821cdcb820"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("f75fc379-eb23-49ad-a60e-0b4e0556e7eb"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("05180053-fa51-4263-b26c-c8eb55d0cc2f"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("ad915dfa-0463-4b42-8e33-11b4539f519c"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("b31418a4-070d-42c8-841e-5aa4de008184"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("34706640-abae-4206-b395-8688da213ee4"),
                            UserId = new Guid("5c1cfb37-2a8a-4f71-9ed8-f190cd7302e2")
                        },
                        new
                        {
                            PermissionId = new Guid("07e8ff14-1ce0-457d-970c-69c745eb574e"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("01d254b7-37a9-4693-903d-405bfd06eeb2"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("4e784112-5544-4879-98db-8daaf9082135"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("123192d4-318e-4395-8bfe-fc8ac1e5f6c7"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("25a95351-ac71-4b27-b4a5-ffd76b355d5c"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("31fa3476-ffea-408c-8d11-0e345d9e6e9b"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("966e3761-9e30-4975-9902-7d6d81fc0e54"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("997ac669-bcd1-4d3c-b38a-1c3050a774bf"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("6c074926-8c66-4cbc-8693-b04e64a4ca70"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("aa44e395-8089-478b-9b17-e3aedeb5f887"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("a02296dc-9392-4ef9-9e3d-5af8e889cc7c"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("4285bf3b-2150-4c7d-bde0-2ae392f8c4e8"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("8b401275-21e7-4e67-ac64-98fe95d52fb0"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("0e7edc7b-9688-4f76-a0f7-3baba00dd077"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("f34af2b3-5e49-4183-95a5-05821cdcb820"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("f75fc379-eb23-49ad-a60e-0b4e0556e7eb"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("05180053-fa51-4263-b26c-c8eb55d0cc2f"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("ad915dfa-0463-4b42-8e33-11b4539f519c"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("b31418a4-070d-42c8-841e-5aa4de008184"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        },
                        new
                        {
                            PermissionId = new Guid("34706640-abae-4206-b395-8688da213ee4"),
                            UserId = new Guid("87d33311-fc05-4f1f-a5f0-d090d7ef0a01")
                        });
                });

            modelBuilder.Entity("Domain.SecurityCam", b =>
                {
                    b.HasBaseType("Domain.Device");

                    b.Property<string>("CamSupportedActionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CamSupportedActionsJson");

                    b.Property<string>("UseTypeJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UseTypeJson");

                    b.HasDiscriminator().HasValue("SecurityCam");
                });

            modelBuilder.Entity("Domain.SmartLampHardware", b =>
                {
                    b.HasBaseType("Domain.Hardware");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("SmartLamp");
                });

            modelBuilder.Entity("Domain.WindowSensorHardware", b =>
                {
                    b.HasBaseType("Domain.Hardware");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("WindowSensor");
                });

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.HasOne("Domain.User", "Owner")
                        .WithOne()
                        .HasForeignKey("Domain.Company", "OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Device", b =>
                {
                    b.HasOne("Domain.Company", "Company")
                        .WithMany("Devices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Hardware", b =>
                {
                    b.HasOne("Domain.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Home", "Home")
                        .WithMany("Devices")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.HasOne("Domain.User", "Owner")
                        .WithMany("OwnedHomes")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.UbicationGeo", "Ubication", b1 =>
                        {
                            b1.Property<Guid>("HomeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Lat")
                                .HasColumnType("int");

                            b1.Property<int?>("Lon")
                                .HasColumnType("int");

                            b1.HasKey("HomeId");

                            b1.ToTable("Homes");

                            b1.WithOwner()
                                .HasForeignKey("HomeId");
                        });

                    b.Navigation("Owner");

                    b.Navigation("Ubication")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Notification", b =>
                {
                    b.HasOne("Domain.Hardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Hardware");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.NotificationMember", b =>
                {
                    b.HasOne("Domain.Home", "Home")
                        .WithMany("NotificationMembers")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.SessionUser", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.UserHomePermission", b =>
                {
                    b.HasOne("Domain.Home", "Home")
                        .WithMany("Members")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("HomePermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.UserPermissions", b =>
                {
                    b.HasOne("Domain.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Company", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Domain.Home", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Members");

                    b.Navigation("NotificationMembers");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("HomePermissions");

                    b.Navigation("OwnedHomes");
                });
#pragma warning restore 612, 618
        }
    }
}
